name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Universal macOS Binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o native-host/app.amd64 native-host/app.go
          GOOS=darwin GOARCH=arm64 go build -o native-host/app.arm64 native-host/app.go
          lipo -create -output native-host/app.mac native-host/app.amd64 native-host/app.arm64
          rm native-host/app.amd64 native-host/app.arm64

      - name: Build for Linux (x86_64)
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o native-host/app.linux native-host/app.go

      - name: Package release tarball
        run: |
          rm native-host/app.go
          tar -czvf "extension-manager-${{ github.ref_name }}.tar.gz" \
            --exclude='.git' \
            --exclude='.github' \
            .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "extension-manager-*.tar.gz"
